# Project information
site_name: achieveone's tech-blog
site_url: https://achieveonepark.github.io/cording-library

# Repository
repo_name: achieveonepark
repo_url: https://github.com/achieveonepark/

nav:
    - Home: index.md
    - Unity Packages:
        - Game Framework: Documents/GameFramework/GameFramework.md
        - QuickSave: Documents/QuickSave/QuickSave.md
        - Data Protector: Documents/DataProtector/DataProtector.md
        - LiteDB: Documents/LiteDB/LiteDB.md
        - Smart Addressables: Documents/SmartAddressables/SmartAddressables.md
        - Infinity Value: Documents/InfinityValue/InfinityValue.md
        - Breeze IAP: Documents/BreezeIAP/BreezeIAP.md
        - TableCraft: Documents/TableCraft/TableCraft.md
    - Analysis:
        - Unity IAP 스토어 설정: Analysis/UnityIAP/UnityIAP.md
        - Facebook SDK 17.0.1 iOS Build Issue: Analysis/FacebookSDK/FacebookSDK.md
        - VContainer 분석: Analysis/VContainer/VContainer.md
        - Unity에서 NuGet 사용하기: Analysis/NuGet/NuGet.md
        - Unity Addressables 분석: Analysis/Addressables/Addressables.md
    - DesignPattern:
          - GoF:
               - 행동 패턴:
                    - 책임 연쇄: DesignPattern/GoF/Behavioral/ChainOfResponsibility.md
                    - Command: DesignPattern/GoF/Behavioral/Command.md
                    - Interpreter: DesignPattern/GoF/Behavioral/Interpreter.md
                    - Iterator: DesignPattern/GoF/Behavioral/Iterator.md
                    - Mediator: DesignPattern/GoF/Behavioral/Mediator.md
                    - Memento: DesignPattern/GoF/Behavioral/Memento.md
                    - Observer: DesignPattern/GoF/Behavioral/Observer.md
                    - State: DesignPattern/GoF/Behavioral/State.md
                    - Strategy: DesignPattern/GoF/Behavioral/Strategy.md
                    - 템플릿 메서드: DesignPattern/GoF/Behavioral/TemplateMethod.md
                    - Visitor: DesignPattern/GoF/Behavioral/Visitor.md
               - 구조 패턴:
                      - Adapter: DesignPattern/GoF/Structural/Adapter.md
                      - Bridge: DesignPattern/GoF/Structural/Bridge.md
                      - Composite: DesignPattern/GoF/Structural/Composite.md
                      - Decorator: DesignPattern/GoF/Structural/Decorator.md
                      - Facade: DesignPattern/GoF/Structural/Facade.md
                      - FactoryMethod: DesignPattern/GoF/Structural/FactoryMethod.md
                      - Flyweight: DesignPattern/GoF/Structural/Flyweight.md
                      - Proxy: DesignPattern/GoF/Structural/Proxy.md
               - 생성 패턴:
                      - 추상 팩토리: DesignPattern/GoF/Creational/AbstractFactory.md
                      - Builder: DesignPattern/GoF/Creational/Builder.md
                      - Prototype: DesignPattern/GoF/Creational/Prototype.md
                      - Singleton: DesignPattern/GoF/Creational/Singleton.md
          - Game Programming:
               - Component: DesignPattern/GameProgramming/Component.md
               - DataLocality: DesignPattern/GameProgramming/DataLocality.md
               - DirtyFlag: DesignPattern/GameProgramming/DirtyFlag.md
               - EventQueue: DesignPattern/GameProgramming/EventQueue.md
               - GameLoop: DesignPattern/GameProgramming/GameLoop.md
               - ObjectPool: DesignPattern/GameProgramming/ObjectPool.md
               - ServiceLocator: DesignPattern/GameProgramming/ServiceLocator.md
               - Subclass Sandbox: DesignPattern/GameProgramming/SubclassSandbox.md
               - TypeObject: DesignPattern/GameProgramming/TypeObject.md
theme:
  name: material
plugins:
  - search
  - mermaid2:
     version: '9.4.3'
     arguments:
       theme: 'default'
       themeVariables:
         primaryColor: '#FFA500'
         primaryTextColor: '#000000'
         primaryBorderColor: '#FF4500'
         lineColor: '#32CD32'
         secondaryColor: '#FFFAE3'
         tertiaryColor: '#FFD700'